language: node_js
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
node_js:
  - 8
  - 10
  - 11
before_install:
  - npm install -g greenkeeper-lockfile@2
install:
  - npm install
  - npm install -g codecov
before_script: greenkeeper-lockfile-update
script:
  - npm run test
  - codecov
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"